/* Fraser & dialoger — skördade ur källdokumentets situationsavsnitt,
   rättade till systemet: pǒm ej chǎn, g/k/bp/dt/p, o=å, ue, oy, kráp.
   Varje scen = körklara repliker man kan säga rakt av. */

const T = {'à':1,'è':1,'ì':1,'ò':1,'ù':1,'â':2,'ê':2,'î':2,'ô':2,'û':2,
           'á':3,'é':3,'í':3,'ó':3,'ú':3,'ǎ':4,'ě':4,'ǐ':4,'ǒ':4,'ǔ':4};
const _t = ph => ph.split(/[\s-]+/).filter(Boolean).map(s => {
  for (const c of s) if (T[c] !== undefined) return T[c]; return 0;
});
// rad: [thai, fonetik, svenska, (valfri not)]
const R = (th, ph, sv, note) => ({ th, ph, sv, t: _t(ph), note });

window.DIALOGS = [
  {
    id: "restaurang",
    n: "På restaurangen",
    e: "🍽️",
    lead: "Från att du kliver in till att maten står på bordet. Fraserna nedan tar dig genom hela besöket.",
    rows: [
      R("มีโต๊ะว่างไหมครับ", "mii dtó wâang mǎi kráp", "Har ni ett ledigt bord?"),
      R("สำหรับสองคนครับ", "sǎm-ràp sǒng kon kráp", "För två personer."),
      R("ขอเมนูหน่อยครับ", "kǒ mee-nuu nòy kráp", "Kan jag få menyn, tack?"),
      R("คุณแนะนำอะไรครับ", "kun náe-nam à-rai kráp", "Vad rekommenderar du?"),
      R("อันนี้เผ็ดไหมครับ", "an-níi pèt mǎi kráp", "Är den här stark?"),
      R("ขอไม่เผ็ดมากครับ", "kǒ mâi pèt mâak kráp", "Inte så starkt, tack."),
      R("ผมจะสั่งผัดไทยครับ", "pǒm jà sàng pàt-tai kráp", "Jag beställer pad thai."),
      R("ขอข้าวเพิ่มหน่อยครับ", "kǒ kâao pôem nòy kráp", "Kan jag få mer ris?"),
      R("อร่อยมากครับ", "à-ròy mâak kráp", "Väldigt gott!"),
      R("ขอบิลหน่อยครับ", "kǒ bin nòy kráp", "Notan, tack."),
    ],
  },
  {
    id: "utan",
    n: "Säg vad du inte vill ha",
    e: "🚫",
    lead: "Mönstret är alltid detsamma: mâi sài + det du vill undvika. Oumbärligt om du har allergier eller inte tål starkt.",
    rows: [
      R("ไม่ใส่พริกครับ", "mâi sài prík kráp", "Utan chili.", "Livsviktig fras om du inte tål starkt"),
      R("ไม่ใส่ผักครับ", "mâi sài pàk kráp", "Utan grönsaker."),
      R("ไม่ใส่ไข่ครับ", "mâi sài kài kráp", "Utan ägg."),
      R("ไม่ใส่ถั่วครับ", "mâi sài tùa kráp", "Utan jordnötter.", "tùa = bönor/jordnötter — viktigt vid allergi"),
      R("ไม่ใส่กุ้งครับ", "mâi sài gûng kráp", "Utan räkor."),
      R("ไม่ใส่น้ำปลาครับ", "mâi sài náam-bplaa kráp", "Utan fisksås."),
      R("ไม่ใส่น้ำตาลครับ", "mâi sài náam-dtaan kráp", "Utan socker."),
      R("ผมกินมังสวิรัติครับ", "pǒm gin mang-sà-wí-rát kráp", "Jag är vegetarian.", "★ tillägg — inte i källan men mycket användbart"),
    ],
  },
  {
    id: "cafe",
    n: "På caféet",
    e: "☕",
    lead: "Kaffebeställningen, från varm till iskall. Thailändskt kaffe är sött som standard — vill du inte ha socker måste du säga till.",
    rows: [
      R("ขอกาแฟร้อนครับ", "kǒ gaa-fae rón kráp", "En varm kaffe, tack."),
      R("ขอกาแฟเย็นครับ", "kǒ gaa-fae yen kráp", "En iskaffe, tack."),
      R("ขอกาแฟดำครับ", "kǒ gaa-fae dam kráp", "En svart kaffe, tack."),
      R("ใส่นมด้วยครับ", "sài nom dûai kráp", "Med mjölk, tack."),
      R("ไม่ใส่น้ำตาลครับ", "mâi sài náam-dtaan kráp", "Utan socker."),
      R("ขอน้ำตาลนิดหน่อยครับ", "kǒ náam-dtaan nít-nòy kráp", "Lite socker, tack."),
      R("เพิ่มน้ำแข็งได้ไหมครับ", "pôem náam-kǎeng dâi mǎi kráp", "Kan jag få extra is?"),
      R("ห่อกลับบ้านครับ", "hò glàp bâan kráp", "Ta med, tack.", "Ordagrant: slå in och ta hem"),
      R("ดื่มที่นี่ครับ", "dùem tîi-nîi kráp", "Jag dricker här."),
    ],
  },
  {
    id: "taxi",
    n: "I taxin",
    e: "🚕",
    lead: "Kom överens om att mätaren används innan du åker, och styr färden med de här korta kommandona.",
    rows: [
      R("ไปสนามบินครับ", "bpai sà-nǎam-bin kráp", "Till flygplatsen, tack."),
      R("เปิดมิเตอร์ได้ไหมครับ", "bpòet mí-dtôe dâi mǎi kráp", "Kan du slå på mätaren?", "Nyckelfråga — annars kan priset bli påhittat"),
      R("ไปที่นี่ครับ", "bpai tîi-nîi kráp", "Kör hit, tack.", "Peka på en adress eller karta"),
      R("เลี้ยวซ้ายครับ", "líao sáai kráp", "Sväng vänster."),
      R("เลี้ยวขวาครับ", "líao kwǎa kráp", "Sväng höger."),
      R("ตรงไปครับ", "dtrong-bpai kráp", "Rakt fram."),
      R("จอดตรงนี้ครับ", "jòt dtrong-níi kráp", "Stanna här, tack."),
      R("ขับช้าๆ หน่อยครับ", "kàp cháa-cháa nòy kráp", "Kör lite långsammare."),
      R("เท่าไหร่ครับ", "tâo-rài kráp", "Hur mycket kostar det?"),
    ],
  },
  {
    id: "hotell",
    n: "På hotellet",
    e: "🏨",
    lead: "Från incheckning till problem med rummet. Sista raden är den du önskar att du kunde när AC:n slutar fungera.",
    rows: [
      R("ผมจองห้องไว้แล้วครับ", "pǒm jong hông wái láew kráp", "Jag har bokat ett rum."),
      R("มีห้องว่างไหมครับ", "mii hông wâang mǎi kráp", "Har ni lediga rum?"),
      R("ห้องผมอยู่ชั้นไหนครับ", "hông pǒm yùu chán nǎi kráp", "Vilken våning ligger mitt rum på?"),
      R("ขอกุญแจห้องครับ", "kǒ gun-jae hông kráp", "Kan jag få rumsnyckeln?"),
      R("ที่จอดรถอยู่ไหนครับ", "tîi-jòt-rót yùu nǎi kráp", "Var är parkeringen?"),
      R("อาหารเช้ากี่โมงครับ", "aa-hǎan-cháo gìi moong kráp", "När serveras frukost?"),
      R("แอร์เสียครับ", "ae sǐa kráp", "AC:n är trasig.", "sǐa = trasig/går sönder — funkar för allt som inte fungerar"),
      R("ขอผ้าเช็ดตัวเพิ่มครับ", "kǒ pâa-chét-dtua pôem kráp", "Kan jag få fler handdukar?"),
    ],
  },
  {
    id: "flygplats",
    n: "På flygplatsen",
    e: "✈️",
    lead: "Hitta rätt och håll koll på ditt flyg. Kortare fraser här — på flygplatsen pekar och visar man mycket.",
    rows: [
      R("เช็คอินที่ไหนครับ", "chék-in tîi-nǎi kráp", "Var checkar man in?"),
      R("ประตูอยู่ไหนครับ", "bprà-dtuu yùu nǎi kráp", "Var ligger gaten?"),
      R("เที่ยวบินออกกี่โมงครับ", "tîao-bin òk gìi moong kráp", "Vilken tid går flyget?"),
      R("เที่ยวบินล่าช้าไหมครับ", "tîao-bin lâa-cháa mǎi kráp", "Är flyget försenat?"),
      R("กระเป๋าผมหายครับ", "grà-bpǎo pǒm hǎai kráp", "Min väska är borta.", "hǎai = försvinna/tappas bort"),
      R("ห้องน้ำอยู่ไหนครับ", "hông-náam yùu nǎi kráp", "Var är toaletten?"),
    ],
  },
  {
    id: "betala",
    n: "Betala",
    e: "💳",
    lead: "Kontant eller kort, och den viktiga frågan om växel. Funkar i butik, på marknad och på restaurang.",
    rows: [
      R("ผมขอจ่ายเงินครับ", "pǒm kǒ jàai ngoen kráp", "Jag vill betala."),
      R("จ่ายด้วยบัตรได้ไหมครับ", "jàai dûai bàt dâi mǎi kráp", "Kan jag betala med kort?", "Många småställen tar bara kontant"),
      R("จ่ายเงินสดครับ", "jàai ngoen-sòt kráp", "Jag betalar kontant."),
      R("มีเงินทอนไหมครับ", "mii ngoen-ton mǎi kráp", "Har du växel?"),
      R("คิดเงินด้วยครับ", "kít ngoen dûai kráp", "Räkningen, tack.", "Vanligare än 'bin' på enklare ställen"),
      R("แพงไปครับ", "paeng bpai kráp", "Det är för dyrt.", "Artig invändning vid prutning"),
      R("ลดหน่อยได้ไหมครับ", "lót nòy dâi mǎi kráp", "Kan du sänka priset lite?", "★ tillägg — prutfras för marknaden"),
    ],
  },
  {
    id: "shopping",
    n: "Handla & prova kläder",
    e: "🛍️",
    lead: "Fråga efter storlek, prova, och säg vad du tycker. Pekfingret är din vän — men de här fraserna tar dig längre.",
    rows: [
      R("อันนี้เท่าไหร่ครับ", "an-níi tâo-rài kráp", "Vad kostar den här?"),
      R("มีไซส์ใหญ่กว่านี้ไหมครับ", "mii sai yài gwàa níi mǎi kráp", "Har ni en större storlek?"),
      R("ลองได้ไหมครับ", "long dâi mǎi kráp", "Får jag prova?"),
      R("ห้องลองอยู่ไหนครับ", "hông long yùu nǎi kráp", "Var är provrummet?"),
      R("เล็กไปครับ", "lék bpai kráp", "Den är för liten."),
      R("ใหญ่ไปครับ", "yài bpai kráp", "Den är för stor."),
      R("มีสีอื่นไหมครับ", "mii sǐi ùen mǎi kráp", "Finns den i andra färger?"),
      R("ผมเอาอันนี้ครับ", "pǒm ao an-níi kráp", "Jag tar den här."),
      R("ไม่เอาถุงครับ", "mâi ao tǔng kráp", "Ingen påse, tack."),
    ],
  },
  {
    id: "hurmycket",
    n: "Hur mycket & hur många",
    e: "🔢",
    lead: "Två olika ord: tâo-rài för pris och mängd du inte räknar, gìi för sådant du räknar i stycken. PDF:ens grammatikpunkt, som körklara frågor.",
    rows: [
      R("ราคาเท่าไหร่ครับ", "raa-kaa tâo-rài kráp", "Hur mycket kostar det?", "tâo-rài = hur mycket (pris)"),
      R("อันนี้เท่าไหร่ครับ", "an-níi tâo-rài kráp", "Vad kostar den här?"),
      R("กี่บาทครับ", "gìi bàat kráp", "Hur många baht?", "gìi = hur många (räknbart)"),
      R("กี่คนครับ", "gìi kon kráp", "Hur många personer?"),
      R("กี่ชั่วโมงครับ", "gìi chûa-moong kráp", "Hur många timmar?"),
      R("นานไหมครับ", "naan mǎi kráp", "Tar det lång tid?"),
      R("ไกลไหมครับ", "glai mǎi kráp", "Är det långt?"),
    ],
  },
  {
    id: "vardag",
    n: "Prata med folk",
    e: "💬",
    lead: "Det sociala smörjmedlet. 'Har du ätit?' är thailändarnas 'hur mår du' — svara sà-baai-dii oavsett.",
    rows: [
      R("สวัสดีครับ", "sà-wàt-dii kráp", "Hej."),
      R("สบายดีไหมครับ", "sà-baai-dii mǎi kráp", "Hur mår du?"),
      R("สบายดีครับ", "sà-baai-dii kráp", "Jag mår bra."),
      R("กินข้าวหรือยังครับ", "gin kâao rǔe yang kráp", "Har du ätit?", "Vänlig hälsning — inte en bokstavlig fråga"),
      R("คุณชื่ออะไรครับ", "kun chûe à-rai kráp", "Vad heter du?"),
      R("ผมชื่อ...ครับ", "pǒm chûe ... kráp", "Jag heter ...", "Sätt in ditt namn"),
      R("ยินดีที่ได้รู้จักครับ", "yin-dii tîi dâi rúu-jàk kráp", "Trevligt att träffas."),
      R("ขอโทษครับ", "kǒ-tôot kráp", "Ursäkta / förlåt."),
      R("ไม่เป็นไรครับ", "mâi-bpen-rai kráp", "Ingen fara.", "Thailands mest användbara fras"),
      R("แล้วเจอกันครับ", "láew joe gan kráp", "Vi ses."),
    ],
  },
];
